{% set name = "orbax-checkpoint" %}
{% set version = "0.11.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/orbax_checkpoint-{{ version }}.tar.gz
  sha256: de7c3826550fc5fed1eb362be30e4b83125cb32bb86de951652bb3c4f9337415

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0

requirements:
  host:
    - python
    - flit-core >=3.5,<4
    - pip
  run:
    - python
    - absl-py
    - etils
    - typing_extensions
    - msgpack-python
    - jax >=0.5.0
    - numpy
    - pyyaml
    - tensorstore >=0.1.71
    - nest-asyncio
    - protobuf
    - humanize
    - simplejson >=3.16.0
    - importlib_resources

test:
  files:
    - test_smoke_orbax_checkpoint.py
  imports:
    - orbax.checkpoint
  requires:
    - pip
    - python
    - pytest
    - numpy
    - jax
    - importlib_resources
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -v test_smoke_orbax_checkpoint.py

about:
  home: https://github.com/google/orbax
  summary: Orbax provides common checkpointing and persistence utilities for JAX users
  description: |
    Orbax includes a checkpointing library oriented towards JAX users,
    supporting a variety of different features required by different frameworks,
    including asynchronous checkpointing, various types, and various storage formats.
    We aim to provide a highly customizable and composable API which maximizes
    flexibility for diverse use cases.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://orbax.readthedocs.io
  dev_url: https://github.com/google/orbax

extra:
  recipe-maintainers:
    - jan-janssen
    - bwohlberg
